import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import StarryBackground from "@/components/ui/StarryBackground/StarryBackground";
import Header from "@/components/ui/Header/Header";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="fr">
      <head>
        <style>
          {`
            ::-webkit-scrollbar {
              width: 8px;
            }
            ::-webkit-scrollbar-track {
              background:rgb(17, 17, 17);
            }
            ::-webkit-scrollbar-thumb {
              background: rgba(148, 163, 184, 0.3);
              border-radius: 4px;
            }
            ::-webkit-scrollbar-thumb:hover {
              background: rgba(148, 163, 184, 0.5);
            }
            * {
              scrollbar-width: thin;
              scrollbar-color: rgba(148, 163, 184, 0.3) rgb(17, 17, 17);
              box-sizing: border-box;
            }
            body {
              margin: 0;
              padding: 0;
              overflow-x: hidden;
              width: 100%;
            }
          `}
        </style>
      </head>
      <body style={{
        fontFamily: 'var(--font-montserrat)',
        minHeight: '100vh',
        margin: 0,
        padding: 0,
        width: '100%',
        overflowX: 'hidden',
        position: 'relative'
      }} className={montserrat.variable}>
        <StarryBackground />
        <Header />
        <main style={{
          paddingTop: '70px',
          position: 'relative',
          zIndex: 1,
          width: '100%',
          maxWidth: '100%',
          overflowX: 'hidden'
        }}>
          {children}
        </main>
      </body>
    </html>
  );
}
