import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import StarryBackground from "@/components/ui/StarryBackground/StarryBackground";
import Header from "@/components/ui/Header/Header";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="fr">
      <body style={{fontFamily: 'var(--font-montserrat)', height: '100vh', margin: 0, padding: 0, width: '100vw', overflowX: 'hidden'}} className={montserrat.variable}>
        <StarryBackground />
        <Header />
        <main style={{
          paddingTop: '70px', // Pour compenser la hauteur du header fixe
          position: 'relative',
          zIndex: 1
        }}>
          {children}
        </main>
      </body>
    </html>
  );
}
